const SALT_ROUND = 10;
const OLD_PASSWORD_MANAGER = "OLD_PASSWORD_MANAGER";

const PERMISSION_CODE = {
    READ: "READ",
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    MANAGER: "MANAGER"
};

const MEDIA_TYPE = {
    AUDIO: "AUDIO",
    VIDEO: "VIDEO",
    IMAGE: "IMAGE",
    OTHER: "OTHER",
};

const SONG_STATUS = {
    PRIVATE: 0,
    ACTIVE: 1,
    PENDING: 2
};

module.exports = {
    SALT_ROUND,
    PERMISSION_CODE,
    MEDIA_TYPE,
    SONG_STATUS
};
